In [1]:
import numpy as np;

### 1.Create a 4X2 integer array and Prints its attributes     OR  How to get the positions where elements of two arrays match? 

In [2]:
x = np.arange(8).reshape(4,2)
print("The Array is",x)
print("Shape :",x.shape)
print("Maximum : ",x.max())
print("Minimum : ",x.min())
print("index of maximum : ",x.argmax())
print("index of minimum : ",x.argmin())
print("Dimensions :",x.ndim)
print("Base :",x.base)

The Array is [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Shape : (4, 2)
Maximum :  7
Minimum :  0
index of maximum :  7
index of minimum :  0
Dimensions : 2
Base : [0 1 2 3 4 5 6 7]


### OR

In [3]:
a = np.array([1,2,3,4,5,6])
b = np.array([0,2,6,4,10,6])
print(np.where(a==b))

(array([1, 3, 5], dtype=int32),)


### 2. Create a 5X2 integer array from a range between 100 to 300 such that the difference between each  element is 20. 

In [4]:
a = np.arange(100,300,20).reshape(5,2)
print(a,a.shape)

[[100 120]
 [140 160]
 [180 200]
 [220 240]
 [260 280]] (5, 2)


### 3. Following is the given numpy array return array of odd rows and even columns import numpy sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],  [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 

In [5]:
import numpy 
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],  [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print("If we start numbering from 1")
print(sampleArray[0::2,1::2])
print("If we start numbering from 0")
print(sampleArray[1::2,0::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
If we start numbering from 1
[[ 6 12]
 [30 36]
 [54 60]]
If we start numbering from 0
[[15 21]
 [39 45]]


### 4.Write a NumPy program to create an array of 5 zeros, 5 ones, 5 fives.

In [6]:
zero = np.zeros(5)
ones = np.ones(5)
fives = ones*5
x = np.concatenate((zero,ones,fives))
print(x)

[0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 5. 5. 5. 5. 5.]


### 5.Write a NumPy program to create a 4X5 array using and iterate over it.

In [7]:
a = np.arange(20).reshape(4,5)
print(a)
for i in a:
    for j in i:
        print(j)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### 6. Write a NumPy program to get the number of items, array dimensions, number of array dimensions and  the memory size of each element of a given array. 

In [8]:
x = np.array([10,20,1,798,12,90]).reshape(2,3)
print("The Array is :",x)
print("The Dimentions :",x.ndim)
print("The Shape :",x.shape)
print("The Size :",x.size)
print("Total Memory Size :",x.nbytes)
print("Size of one element :",x.nbytes / x.size)
print("Datatype :",x.dtype)

The Array is : [[ 10  20   1]
 [798  12  90]]
The Dimentions : 2
The Shape : (2, 3)
The Size : 6
Total Memory Size : 24
Size of one element : 4.0
Datatype : int32


### 7. Write a NumPy program to get the unique elements of an array. 

In [9]:
x = np.array([1,12,2,4,3,5,6,1,2,5,2,2,5,0,4,5,0,3,7,3,12])
print("The origional Array : ",x)
print("The unique elements :",np.unique(x))

The origional Array :  [ 1 12  2  4  3  5  6  1  2  5  2  2  5  0  4  5  0  3  7  3 12]
The unique elements : [ 0  1  2  3  4  5  6  7 12]


### 8.Write a NumPy program to create a contiguous flattened array. 

In [10]:
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(x)
y = np.ravel(x)
print("New flattened array:")
print(y)

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


### 9.Write a NumPy program to change the data type of an array. 

In [11]:
x = np.array([1.1,1.2,2.4,3.2,4.6,4.2,6.2])
print("The Array is :",x)
print("Datatype of x:",x.dtype)
x = x.astype('i4')
print("Now the array is:",x)
print("Datatype of x:",x.dtype)

The Array is : [1.1 1.2 2.4 3.2 4.6 4.2 6.2]
Datatype of x: float64
Now the array is: [1 1 2 3 4 4 6]
Datatype of x: int32


### 10. Write a NumPy program to create a 2-D array whose diagonal equals [1,2,3,4] and 0's elsewhere. 

In [12]:
x = np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### 11.Write a NumPy program to create an array of three column types (integer, float, character). 

In [13]:
x = np.array([1,2,3],dtype=('i,f,c'))
a = [(1, 1.01, "A"), (2, 2.02, "B"), (3, 3.03, "C")]
x[:] = a
print(x)
print(x.dtype)

[(1, 1.01, b'A') (2, 2.02, b'B') (3, 3.03, b'C')]
[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S1')]


### 12.Write a NumPy program to count the frequency of unique values in NumPy array. 

In [14]:
x = np.array([1,12,2,4,3,5,6,1,2,5,2,2,5,0,4,5,0,3,7,3,12])
print("The array is:",x)
elements, counts = np.unique(x, return_counts=True)
print("Frequency of unique values of the said array:")
for i,j in zip(elements,counts):
    print("{} times {}".format(j,i))

The array is: [ 1 12  2  4  3  5  6  1  2  5  2  2  5  0  4  5  0  3  7  3 12]
Frequency of unique values of the said array:
2 times 0
2 times 1
4 times 2
3 times 3
2 times 4
4 times 5
1 times 6
1 times 7
2 times 12


### 13.How to create a boolean array? 

In [15]:
x = np.array([True,False,True,False,True])
print(x)
print("The Datatype :",x.dtype)

[ True False  True False  True]
The Datatype : bool


### 14.How to replace items that satisfy a condition without affecting the original array? 

In [16]:
x = np.arange(1,21)
print(x)
print("The evens will be replaced by 1 and odds are 0 ")
print(np.where(x%2==0,1,0))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The evens will be replaced by 1 and odds are 0 
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


### 15.How to remove from one array those items that exist in another?

In [17]:
x = np.arange(1,21,2)
y = np.arange(1,21,3)
print("x : ",x)
print("y : ",y)
print("After Removing the elements :")
x = np.setdiff1d(x,y)
print("x : ",x)

x :  [ 1  3  5  7  9 11 13 15 17 19]
y :  [ 1  4  7 10 13 16 19]
After Removing the elements :
x :  [ 3  5  9 11 15 17]
