In [1]:
import pandas as pd
import numpy as np

### 1. Import Car Sales data

In [2]:
cardf = pd.read_csv('Car_sales.csv')

In [3]:
cardf

Manufacturer              Model  Sales in thousands  x_4_year  \
0    Acura          Integra                        16.919    16.360   
1    Acura          TL                             39.384    19.875   
2    Acura          CL                             14.114    18.225   
3    Acura          RL                              8.588    29.725   
4    Audi           A4                             20.397    22.255   
..             ...                ...                 ...       ...   
152  Volvo          V40                             3.545       NaN   
153  Volvo          S70                            15.245       NaN   
154  Volvo          V70                            17.531       NaN   
155  Volvo          C70                             3.493       NaN   
156  Volvo          S80                            18.969       NaN   

    Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  \
0      Passenger               21.50          1.8       140.0      101.2   
1      Passenger               28.40          3.2       225.0      108.1   
2      Passenger                 NaN          3.2       225.0      106.9   
3      Passenger               42.00          3.5       210.0      114.6   
4      Passenger               23.99          1.8       150.0      102.6   
..           ...                 ...          ...         ...        ...   
152    Passenger               24.40          1.9       160.0      100.5   
153    Passenger               27.50          2.4       168.0      104.9   
154    Passenger               28.80          2.4       168.0      104.9   
155    Passenger               45.50          2.3       236.0      104.9   
156    Passenger               36.00          2.9       201.0      109.9   

     Width  Length  Curb weight  Fuel capacity  Fuel efficiency Latest Launch  \
0     67.3   172.4        2.639           13.2             28.0      2-Feb-14   
1     70.3   192.9        3.517           17.2             25.0      6-Mar-15   
2     70.6   192.0        3.470           17.2             26.0      1-Apr-14   
3     71.4   196.6        3.850           18.0             22.0      3-Oct-15   
4     68.2   178.0        2.998           16.4             27.0     10-Aug-15   
..     ...     ...          ...            ...              ...           ...   
152   67.6   176.6        3.042           15.8             25.0     21-Sep-15   
153   69.3   185.9        3.208           17.9             25.0     24-Nov-14   
154   69.3   186.2        3.259           17.9             25.0     25-Jun-15   
155   71.5   185.7        3.601           18.5             23.0     26-Apr-15   
156   72.1   189.8        3.600           21.1             24.0     14-Nov-15   

     Unnamed: 15      XX  
0            NaN  16.360  
1            NaN  19.875  
2            NaN  18.225  
3            NaN  29.725  
4            NaN  22.255  
..           ...     ...  
152          NaN     NaN  
153          NaN     NaN  
154          NaN     NaN  
155          NaN     NaN  
156          NaN     NaN  

[157 rows x 17 columns]

### 3. Treat all the missing values with mean/median or most occuring observation

In [4]:
cardf.isnull().sum()

Manufacturer            3
Model                   0
Sales in thousands      0
x_4_year               36
Vehicle type            0
Price in thousands      2
Engine size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb weight             2
Fuel capacity           1
Fuel efficiency         3
Latest Launch           0
Unnamed: 15           157
XX                     36
dtype: int64

In [5]:
cardf['Manufacturer'].fillna(value=cardf['Manufacturer'].mode()[0],inplace=True)
cardf['x_4_year'].fillna(value=cardf['x_4_year'].mean(),inplace=True)
cardf['Price in thousands'].fillna(value=cardf['Price in thousands'].mean(),inplace=True)
cardf['Engine size'].fillna(value=cardf['Engine size'].mean(),inplace=True)
cardf['Horsepower'].fillna(value=cardf['Horsepower'].mean(),inplace=True)
cardf['Horsepower'].fillna(value=cardf['Horsepower'].mean(),inplace=True)
cardf['Wheelbase'].fillna(value=cardf['Wheelbase'].mean(),inplace=True)
cardf['Width'].fillna(value=cardf['Width'].mean(),inplace=True)
cardf['Length'].fillna(value=cardf['Length'].mean(),inplace=True)
cardf['Curb weight'].fillna(value=cardf['Curb weight'].mean(),inplace=True)
cardf['Fuel capacity'].fillna(value=cardf['Fuel capacity'].mean(),inplace=True)
cardf['Fuel efficiency'].fillna(value=cardf['Fuel efficiency'].mean(),inplace=True)
cardf['XX'].fillna(value=cardf['XX'].mean(),inplace=True)

In [6]:
cardf.isnull().sum()

Manufacturer            0
Model                   0
Sales in thousands      0
x_4_year                0
Vehicle type            0
Price in thousands      0
Engine size             0
Horsepower              0
Wheelbase               0
Width                   0
Length                  0
Curb weight             0
Fuel capacity           0
Fuel efficiency         0
Latest Launch           0
Unnamed: 15           157
XX                      0
dtype: int64

### 4. Check for the No. of rows and No. of Column in Car Data

In [7]:
row,col = cardf.shape
print("Rows :",row)
print('Col :',col)

Rows : 157
Col : 17


### 7. Remove unnecessary columns from the data, depending on your own understandings from cars data

In [8]:
cardf.drop(['Unnamed: 15'],axis=1,inplace=True)

#### 7.1 Fetch the name of the model and company's name which have lowest sales.

In [9]:
cardf.loc[cardf['Sales in thousands'].idxmin(),['Manufacturer','Model']]

Manufacturer        Mitsubishi   
Model           3000GT           
Name: 83, dtype: object

#### 7.2 Fetch the name of the model and company's name which have Highest sales.

In [10]:
cardf.loc[cardf['Sales in thousands'].idxmax(),['Manufacturer','Model']]

Manufacturer        Ford         
Model           F-Series         
Name: 56, dtype: object

#### 7.3 Fetch the name of the model and company's name which have lowest sales with respect to Vehicle Type Passenger

In [11]:
cardf.loc[cardf['Vehicle type'] == 'Passenger'].loc[cardf['Sales in thousands'].idxmin(),['Manufacturer','Model']]

Manufacturer        Mitsubishi   
Model           3000GT           
Name: 83, dtype: object

#### 7.4 Fetch the name of the model and company's name which have Highest sales with respect to Engine Size > 6

In [12]:
cardf.loc[cardf['Engine size'] >6,['Manufacturer','Model'] ]

Manufacturer              Model
39  Dodge          Viper

#### 7.5 Fetch the company name who have got highest mileage with respect to Vehicle Type as Car

In [13]:
cars = cardf.loc[cardf['Vehicle type'] == 'Car']
cars.loc[cars['Fuel efficiency'].idxmax(),['Manufacturer']]

Manufacturer    Toyota       
Name: 142, dtype: object

#### 7.6 Fetch the company name who has got lowest mileage with respect to Vehicle Type as Passengers.

In [14]:
cars = cardf.loc[cardf['Vehicle type'] == 'Passenger']
cars.loc[cars['Fuel efficiency'].idxmin(),['Manufacturer']]

Manufacturer    Dodge        
Name: 39, dtype: object

#### 7.7 Fetch the company name who has got least price and maximum number of sales figures.

In [15]:
cardf['Price in thousands'].min()

9.235

In [16]:
cardf.loc[(cardf['Price in thousands'] / cardf['Sales in thousands']).idxmin(),'Manufacturer']

'Ford         '

#### 7.8 Fetch the company name who has got highest price and minimum number of sales figures.

In [17]:
cardf.loc[(cardf['Price in thousands'] / cardf['Sales in thousands']).idxmax(),'Manufacturer']

'Mitsubishi   '

#### 7.9 Fetch the model who has got maximum number of Horsepower

In [18]:
cardf.loc[cardf['Horsepower'].idxmax(),'Model']

'Viper            '

#### 7.10 Fetch the model and company name who has got maximum mileage with lowest sales figures

In [19]:
cardf.loc[(cardf['Fuel efficiency'] / cardf['Sales in thousands']).idxmax(),'Manufacturer']

'Mitsubishi   '

#### 7.11 Fetch the model and company name who has got minimum mileage with highest sales figures.

In [20]:
cardf.loc[(cardf['Fuel efficiency'] / cardf['Sales in thousands']).idxmin(),'Manufacturer']

'Ford         '

#### 7.12 Fetch the model and company name where the wheel base is maximum with Vehicle type as Car

In [21]:
cars = cardf.loc[cardf['Vehicle type'] == 'Car']
cars.loc[cars['Wheelbase'].idxmax(),['Manufacturer','Model']]

Manufacturer        Dodge        
Model           Ram Pickup       
Name: 40, dtype: object

#### 7.13 Fetch the model and company name where the wheel base is minimum with Vehicle type as Passengers

In [22]:
cars = cardf.loc[cardf['Vehicle type'] == 'Passenger']
cars.loc[cars['Wheelbase'].idxmin(),['Manufacturer','Model']]

Manufacturer        Porsche      
Model           Carrera Coupe    
Name: 125, dtype: object

#### 7.14 Fetch the model and company name where the curb weight is maximum with maximum mileage

In [25]:
cardf.loc[(cardf['Fuel efficiency'] * cardf['Curb weight']).idxmax(),['Manufacturer','Model']]

Manufacturer        Honda        
Model           Odyssey          
Name: 61, dtype: object

#### 7.15 Fetch the model and company name where the curb weight is minimum with maximum mileage

In [26]:
cardf.loc[(cardf['Curb weight']/cardf['Fuel efficiency']).idxmin(),['Manufacturer','Model']]

Manufacturer        Chevrolet    
Model           Metro            
Name: 26, dtype: object

#### 7.16 Fetch the model and company name where the curb weight is minimum with minimum mileage

In [27]:
cardf.loc[(cardf['Fuel efficiency'] * cardf['Curb weight']).idxmin(),['Manufacturer','Model']]

Manufacturer        Jeep         
Model           Wrangler         
Name: 67, dtype: object

#### 7.17 Change the name of column x_4_year to 4_Year_Resale_Valuea

In [30]:
cardf.columns

Index(['Manufacturer', 'Model', 'Sales in thousands', 'x_4_year',
       'Vehicle type', 'Price in thousands', 'Engine size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb weight', 'Fuel capacity',
       'Fuel efficiency', 'Latest Launch', 'XX'],
      dtype='object')

In [31]:
cardf.rename(columns={'x_4_year':'4_Year_Resale_Value'},inplace=True)
cardf.columns

Index(['Manufacturer', 'Model', 'Sales in thousands', '4_Year_Resale_Value',
       'Vehicle type', 'Price in thousands', 'Engine size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb weight', 'Fuel capacity',
       'Fuel efficiency', 'Latest Launch', 'XX'],
      dtype='object')

#### 7.18 Fetch the model and company name whose sales and Resale Value is Highest

In [34]:
cardf.loc[(cardf['Sales in thousands'] * cardf['4_Year_Resale_Value']).idxmax(),['Manufacturer','Model']]

Manufacturer        Ford         
Model           F-Series         
Name: 56, dtype: object

#### 7.19 Fetch the model and company name whose sales, Mileage and Resale Value is Highest but Price is lowest

In [37]:
cardf.loc[(cardf['Sales in thousands'] * cardf['4_Year_Resale_Value'] * cardf['Fuel efficiency'] / cardf['Price in thousands'])
          .idxmax(),['Manufacturer','Model']]

Manufacturer        Ford         
Model           Focus            
Name: 50, dtype: object

#### 7.20 Fethc the model and company name whole resale value is lowest but sale is highest.

In [36]:
cardf.loc[( cardf['4_Year_Resale_Value'] / cardf['Sales in thousands'] ).idxmax(),['Manufacturer','Model']]

Manufacturer        Mitsubishi   
Model           3000GT           
Name: 83, dtype: object

#### 7.21 Replace the observations in Sales colum that are greater than the mean of Sales column

In [38]:
cardf['Sales in thousands'].replace(to_replace=cardf[cardf['Sales in thousands'] >cardf['Sales in thousands'].mean()]
                                    .loc[:,'Sales in thousands'],value=cardf['Sales in thousands'].mean())

0      16.919
1      39.384
2      14.114
3       8.588
4      20.397
        ...  
152     3.545
153    15.245
154    17.531
155     3.493
156    18.969
Name: Sales in thousands, Length: 157, dtype: float64

#### 7.22 Replace the observations in Price column that are greater than the mean of Price column.

In [39]:
cardf['Price in thousands'].replace(to_replace=cardf[cardf['Price in thousands'] >cardf['Price in thousands'].mean()]
                                    .loc[:,'Price in thousands'],value=cardf['Price in thousands'].mean())

0      21.500000
1      27.390755
2      27.390755
3      27.390755
4      23.990000
         ...    
152    24.400000
153    27.390755
154    27.390755
155    27.390755
156    27.390755
Name: Price in thousands, Length: 157, dtype: float64

#### 7.23 Replace the observations in Horsepower that are greater than the mean of Horsepower column.

In [40]:
cardf['Horsepower'].replace(to_replace=cardf[cardf['Horsepower'] >cardf['Horsepower'].mean()]
                            .loc[:,'Horsepower'],value=cardf['Horsepower'].mean())

0      140.000000
1      185.948718
2      185.948718
3      185.948718
4      150.000000
          ...    
152    160.000000
153    168.000000
154    168.000000
155    185.948718
156    185.948718
Name: Horsepower, Length: 157, dtype: float64

#### 9. Create a range of 1 to 100.
#### 9.1 Create a matrix of 10 rows and 10 columns
#### 9.2 Print the following matrix from the columsn<br>
         [47, 48, 49], 
	a    [57, 58, 59],
	     [67, 68, 69],
	
        [40, 41, 42, 43,]
    b   [50, 51, 52, 53,]
        [60, 61, 62, 63,]

        [32, 33, 34, 35, 36, 37, 38, 39],
        [42, 43, 44, 45, 46, 47, 48, 49],
    c   [52, 53, 54, 55, 56, 57, 58, 59],
        [62, 63, 64, 65, 66, 67, 68, 69],
        [72, 73, 74, 75, 76, 77, 78, 79],

        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
    d   [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],

In [41]:
x = np.arange(1,101)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [42]:
y = x.reshape(10,10)
y

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [43]:
y[4:7,6:9]

array([[47, 48, 49],
       [57, 58, 59],
       [67, 68, 69]])

In [44]:
y[3:8,1:-1] 

array([[32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [52, 53, 54, 55, 56, 57, 58, 59],
       [62, 63, 64, 65, 66, 67, 68, 69],
       [72, 73, 74, 75, 76, 77, 78, 79]])

In [45]:
np.array([x[i:i+10] for i in [19,29,39,49]])

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [46]:
np.array([x[i:i+4] for i in [39,49,59]])

array([[40, 41, 42, 43],
       [50, 51, 52, 53],
       [60, 61, 62, 63]])