# Aggregations: Min, Max, and Everything In Between

Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question.
Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the "typical" values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).

NumPy has fast built-in aggregation functions for working on arrays; we'll discuss and demonstrate some of them here.

## Summing the Values in an Array

As a quick example, consider computing the sum of all values in an array.
Python itself can do this using the built-in ``sum`` function:

In [1]:
import numpy as np

In [ ]:
L = np.random.......(100)
...(L)

55.61209116604941

In [2]:
L = np.random.rand(100)
sum(L)

53.49674355109842

The syntax is quite similar to that of NumPy's ``sum`` function, and the result is the same in the simplest case:

In [ ]:
np....(..)

55.612091166049424

In [3]:
np.sum(L)

53.496743551098405

However, because it executes the operation in compiled code, NumPy's version of the operation is computed much more quickly:

In [ ]:
big_array = np...........(1000000)
%timeit ....(big_array)
%timeit np........

10 loops, best of 3: 104 ms per loop
1000 loops, best of 3: 442 µs per loop


In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

526 ms ± 48.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.85 ms ± 79.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Be careful, though: the ``sum`` function and the ``np.sum`` function are not identical, which can sometimes lead to confusion!
In particular, their optional arguments have different meanings, and ``np.sum`` is aware of multiple array dimensions, as we will see in the following section.

## Minimum and Maximum

Similarly, Python has built-in ``min`` and ``max`` functions, used to find the minimum value and maximum value of any given array:

In [ ]:
.....(big_array), ....(big_array)

(1.1717128136634614e-06, 0.9999976784968716)

In [7]:
max(big_array),min(big_array)

(0.9999983106790641, 2.477850654658553e-07)

NumPy's corresponding functions have similar syntax, and again operate much more quickly:

In [9]:
.....(big_array), ....(big_array)

SyntaxError: invalid syntax (<ipython-input-9-acd46d3320ca>, line 1)

In [10]:
np.max(big_array),np.min(big_array)

(0.9999983106790641, 2.477850654658553e-07)

In [ ]:
%timeit ...(......)
%timeit np.min(.......)

10 loops, best of 3: 82.3 ms per loop
1000 loops, best of 3: 497 µs per loop


In [11]:
%timeit min(big_array)
%timeit np.min(big_array)

299 ms ± 6.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
874 µs ± 67.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


For ``min``, ``max``, ``sum``, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself:

In [ ]:
print(big_array....., big_array....., big_array.......)

1.17171281366e-06 0.999997678497 499911.628197


In [14]:
print(big_array.min(), big_array.max(), big_array.sum())

2.477850654658553e-07 0.9999983106790641 500096.48585473455


Whenever possible, make sure that you are using the NumPy version of these aggregates when operating on NumPy arrays!

### Multi dimensional aggregates

One common type of aggregation operation is an aggregate along a row or column.
Say you have some data stored in a two-dimensional array:

In [ ]:
M = np.random.random((....))
print(M)

[[ 0.8967576   0.03783739  0.75952519  0.06682827]
 [ 0.8354065   0.99196818  0.19544769  0.43447084]
 [ 0.66859307  0.15038721  0.37911423  0.6687194 ]]


In [15]:
M = np.random.random((3,4))
print(M)

[[0.3430499  0.26461791 0.65301853 0.58190318]
 [0.85971285 0.51891387 0.29070864 0.77693143]
 [0.03271407 0.86637522 0.88430939 0.72467482]]


By default, each NumPy aggregation function will return the aggregate over the entire array:

In [ ]:
...sum()

6.0850555667307118

In [16]:
M.sum()

6.7969298013413

Aggregation functions take an additional argument specifying the *axis* along which the aggregate is computed. For example, we can find the minimum value within each column by specifying ``axis=0``:

In [ ]:
M.min(......)

array([ 0.66859307,  0.03783739,  0.19544769,  0.06682827])

In [18]:
M.min(axis=0)

array([0.03271407, 0.26461791, 0.29070864, 0.58190318])

The function returns four values, corresponding to the four columns of numbers.

Similarly, we can find the maximum value within each row:

In [ ]:
M.max(....)

array([ 0.8967576 ,  0.99196818,  0.6687194 ])

In [19]:
M.max(axis=1)

array([0.65301853, 0.85971285, 0.88430939])

The way the axis is specified here can be confusing to users coming from other languages.
The ``axis`` keyword specifies the *dimension of the array that will be collapsed*, rather than the dimension that will be returned.
So specifying ``axis=0`` means that the first axis will be collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.

### Other aggregation functions

NumPy provides many other aggregation functions, but we won't discuss them in detail here.
Additionally, most aggregates have a ``NaN``-safe counterpart that computes the result while ignoring missing values, which are marked by the special IEEE floating-point ``NaN`` value (for a fuller discussion of missing data, see [Handling Missing Data](03.04-Missing-Values.ipynb)).
Some of these ``NaN``-safe functions were not added until NumPy 1.8, so they will not be available in older NumPy versions.

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

 

Now that we have this data array, we can compute a variety of summary statistics:

Note that in each case, the aggregation operation reduced the entire array to a single summarizing value, which gives us information about the distribution of values.
We may also wish to compute quantiles:

In [ ]:
////////////////////////////////////----> write your code for any data

In [23]:
heights = np.arange(1,1000,3)

In [ ]:
print("25th percentile:   ", percentile(heights, )
print("Median:            ", median(heights))
print("75th percentile:   ", percentile(heights, ))

25th percentile:    174.25
Median:             182.0
75th percentile:    183.0


In [52]:
print("25th percentile:   ", np.percentile(heights,25 ))
print("Median:            ", np.median(heights) )
print("75th percentile:   ", np.percentile(heights,75 ))

25th percentile:    250.0
Median:             499.0
75th percentile:    748.0


In [53]:
heights

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100, 103, 106, 109, 112, 115,
       118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148, 151, 154,
       157, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193,
       196, 199, 202, 205, 208, 211, 214, 217, 220, 223, 226, 229, 232,
       235, 238, 241, 244, 247, 250, 253, 256, 259, 262, 265, 268, 271,
       274, 277, 280, 283, 286, 289, 292, 295, 298, 301, 304, 307, 310,
       313, 316, 319, 322, 325, 328, 331, 334, 337, 340, 343, 346, 349,
       352, 355, 358, 361, 364, 367, 370, 373, 376, 379, 382, 385, 388,
       391, 394, 397, 400, 403, 406, 409, 412, 415, 418, 421, 424, 427,
       430, 433, 436, 439, 442, 445, 448, 451, 454, 457, 460, 463, 466,
       469, 472, 475, 478, 481, 484, 487, 490, 493, 496, 499, 502, 505,
       508, 511, 514, 517, 520, 523, 526, 529, 532, 535, 538, 54

In [67]:
np.percentile([0,1,5,10],50)

3.0