In [1]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
b = np.arange(10,19).reshape(3,3)
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [4]:
a.trace()

15

In [5]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
a+b

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [7]:
a-b

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [8]:
a*b

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [9]:
a/b

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [15]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
np.matmul(a,b)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [35]:
mata = np.matrix(a)
matb = np.matrix(b)
print(mata)
print(matb)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [31]:
mata*matb

matrix([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

In [34]:
2*mata

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [51]:
i = np.matrix(np.eye(3))

In [52]:
mata.I

matrix([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
        [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
        [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [54]:
(mata.I)*matb

matrix([[  8.,   0.,   0.],
        [  0.,  32.,  32.],
        [ -8., -16., -16.]])

In [64]:
np.math.e

2.718281828459045