In [1]:
import numpy as np

In [2]:
a = np.arange(1,7)
print(a)
a[1:4]

[1 2 3 4 5 6]


array([2, 3, 4])

In [3]:
a[2:]

array([3, 4, 5, 6])

In [4]:
a[:5]

array([1, 2, 3, 4, 5])

In [5]:
a[-3:]

array([4, 5, 6])

In [6]:
a[1:5:2]

array([2, 4])

In [7]:
a[:5:2]

array([1, 3, 5])

In [8]:
b = np.arange(1,11).reshape(2,5)
print(b)
b[:,2:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[3, 4],
       [8, 9]])

In [9]:
b = np.arange(1,9).reshape(2,4)
np.split(b,2,axis=1)

[array([[1, 2],
        [5, 6]]), array([[3, 4],
        [7, 8]])]

In [10]:
b.dtype

dtype('int32')

In [11]:
np.amax(b,axis=0)

array([5, 6, 7, 8])

In [12]:
a.transpose()

array([1, 2, 3, 4, 5, 6])

In [13]:
b.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [14]:
np.array(["a"]).dtype

dtype('<U1')

In [15]:
np.array([True]).dtype

dtype('bool')

In [16]:
np.array([2.90]).dtype

dtype('float64')

In [17]:
np.array([2878865543567845232456789087654321345678987654326789876543245678999]).dtype

dtype('O')

In [18]:
x = np.array([1],dtype=np.int64)
print(x)
print(x.dtype)

[1]
int64


In [19]:
y = np.array([2.342],dtype='i')
print(y)
y.dtype

[2]


dtype('int32')

In [20]:
intY = y.astype('f')
intY

array([2.], dtype=float32)

In [21]:
a = np.arange(10)
print(a.dtype)
print(a)
b = a.astype('f')
print(b)
c = a.astype('bool')
print(c)

int32
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[False  True  True  True  True  True  True  True  True  True]


In [22]:
b = np.arange(1,19,2).reshape(3,3)
b

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [23]:
a = np.arange(1,5)
print(a.nbytes * a.size)

64


In [24]:
#16 byte
a = np.arange(1,5).reshape(2,2)
print(a)
a.nbytes

[[1 2]
 [3 4]]


16

In [25]:
a = np.arange(1,5)
b = a[::-1].astype('f')
print(b)

[4. 3. 2. 1.]


In [26]:
a.tofile("Balgopal.txt",sep=" ")

In [27]:
a = np.array([1,2,3,4])
b = np.array((1,2,3))
print(a,b)

[1 2 3 4] [1 2 3]


In [28]:
x = np.zeros(10)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [29]:
x = np.array([1,2,3,5])
y = np.array([1,5,9])
print(np.union1d(x,y))
np.intersect1d(x,y)


[1 2 3 5 9]


array([1, 5])

In [30]:
np.mat([[1,2],[1,3]])

matrix([[1, 2],
        [1, 3]])

In [31]:
y = np.arange(1,17).reshape(4,4)
x = np.split(y,2)
for i in x:
    print(np.split(i,2,axis=1))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[ 9, 10],
       [13, 14]]), array([[11, 12],
       [15, 16]])]


#### Concat 2 2D Arrays 
#### Collapse a 3D array into 1D

In [50]:
x = np.arange(27).reshape(3,3,3)
print(x)
print(x.shape,x.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
(3, 3, 3) 3


In [77]:
x = np.arange(4).reshape(2,2)
y = np.arange(4,8).reshape(2,2)
print(x,y)
print("Concat in Vertical axis\n",np.concatenate((x,y),axis=0))
print("Concat in horizontal axis\n",np.concatenate((x,y),axis=1))

[[0 1]
 [2 3]] [[4 5]
 [6 7]]
Concat in Vertical axis
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Concat in horizontal axis
 [[0 1 4 5]
 [2 3 6 7]]


### View() and Copy()

In [78]:
a = np.array([1,2,3])
b = a.copy()
c = a.view()
a[1]=4
print(a,b,c)
print(a.base,b.base,c.base)

[1 4 3] [1 2 3] [1 4 3]
None None [1 4 3]


In [79]:
a = np.array([[1,2],[3,4]])
a.shape

(2, 2)

In [80]:
b = np.array([1,2],ndmin=5)
print(b)
b.shape

[[[[[1 2]]]]]


(1, 1, 1, 1, 2)

In [81]:
x = np.array([[1,2],[3,4]])
print(x.ndim)
y = x.reshape(-1)
print(y)
print(y.ndim)

2
[1 2 3 4]
1


In [82]:
z = x.flatten()
print(z)
print(z.base)

[1 2 3 4]
None


In [83]:
x[0,0] = 5
print(x)
print(y)
print(z)

[[5 2]
 [3 4]]
[5 2 3 4]
[1 2 3 4]


### Iterate On Numpy Arrays

In [84]:
a = np.array([1,2,3,4])
for i in a:
    print(i)

1
2
3
4


In [85]:
a = np.array([1,2,3,4]).reshape(2,2)
print(a)
for i in a:
    for j in i:
        print(j)
    

[[1 2]
 [3 4]]
1
2
3
4


In [86]:
for i in np.nditer(a):
    print(i, end=' ')

1 2 3 4 

### Concatinate

In [94]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.stack((a,b),axis=1))
np.stack((a,b))

[[1 4]
 [2 5]
 [3 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [98]:
a = np.arange(1,10)
print(np.array_split(a,5))
np.array_split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [101]:
a = np.arange(1,7).reshape(2,3)
print(a)
print(np.array_split(a,3,axis=1))

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [102]:
a = np.arange(1,5).reshape(2,2)
print(a)
print(np.array_split(a,3,axis=1))

[[1 2]
 [3 4]]
[array([[1],
       [3]]), array([[2],
       [4]]), array([], shape=(2, 0), dtype=int32)]


### Searching Operation

In [12]:
a = np.arange(1,11)
print(a)
print(np.where(a%2 ==0 ))

[ 1  2  3  4  5  6  7  8  9 10]
(array([1, 3, 5, 7, 9], dtype=int32),)


In [13]:
a = np.array([1,2,2,3,3,3,4,5,6,6,2,2,2,6,1])
print(np.where(a==6,1,0))

[0 0 0 0 0 0 0 0 1 1 0 0 0 1 0]


In [14]:
np.who()

Name            Shape            Bytes            Type

a               15               60               int32

Upper bound on total bytes  =       60


#### Set Diffeerence

In [120]:
a = np.arange(1,10,2)
b = np.arange(2,20,3)
print(a,b)
np.setdiff1d(a,b)

[1 3 5 7 9] [ 2  5  8 11 14 17]


array([1, 3, 7, 9])

### Practice Questions

In [134]:
a = np.array([24,123,435,112,543,8,80,8])
print(np.argmax(a),np.argmin(a))

4 5


In [135]:

a = np.diag(1+np.arange(3),k=0)
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [137]:
b = np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [138]:
%pip list

Package            Version
------------------ ----------
api                0.0.7
appdirs            1.4.3
asgiref            3.2.7
astroid            2.3.3
attrs              19.2.0
backcall           0.1.0
beautifulsoup4     4.8.1
bleach             3.1.0
bs4                0.0.1
certifi            2019.11.28
chardet            3.0.4
Click              7.0
colorama           0.4.1
colorlog           4.0.2
cycler             0.10.0
decorator          4.4.0
defusedxml         0.6.0
distlib            0.3.0
Django             3.0.4
docopt             0.6.2
entrypoints        0.3
filelock           3.0.12
Flask              1.1.1
future             0.18.2
gTTS               2.0.4
gTTS-token         1.1.3
idna               2.8
imageio            2.6.1
importlib-metadata 0.23
inflect            3.0.2
ipykernel          5.1.2
ipython            7.8.0
ipython-genutils   0.2.0
ipywidgets         7.5.1
isort              4.3.21
itsdangerous       1.1.0
jaraco.itertools   4.4.2
jedi           